### ISSUE TITLE
Protobuf output for mobile API

### ISSUE THREAD

**Issue by asutula** [textileio/go-textile#454]
**Is your feature request related to a problem? Please describe.**
We'd like to begin work on the native mobile SDK for iOS and Android. Hard to get started with the way the mobile API frameworks are working.

**Describe the solution you'd like**
A version of the mobile API that outputs protobuf data, as well as the .proto files we can use to generate bindings.

**Describe alternatives you've considered**
Just using the current string-ified json data that is coming back now. Using data types natively returned by go-mobile. Neither of these solutions are ideal.

**Additional context**

**Comment by carsonfarmer** [comment]
Can we consider this one 'done' @asutula?
