### ISSUE TITLE
sql: no rows in result set

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/go-textile#465]
**Describe the bug**
After updating to latest release (in this case, Android, but is likely a cross-platform issue), starting the app leads to an sql no rows error.

**To Reproduce**
1. Update to latest release (Android)
2. Open App
3. See error

**Expected behavior**
Expected to start onboarding/migration flow in app.

**Screenshots**
![screenshot_20190117-233759_textile](https://user-images.githubusercontent.com/1220613/51405189-86668780-1b0a-11e9-8182-075966c963ce.jpg)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android Nexus]

**Additional context**
This was after a Play Store update from a relatively recent fresh install.

**Comment by sanderpick** [comment]
Does this happen with _every_ Android migration?

**Comment by carsonfarmer** [comment]
No

**Comment by carsonfarmer** [comment]
I’ve asked for additional information from original reporter. Will update with information once available 👍

**Comment by carsonfarmer** [comment]
Closing this one as 'stale'. Please reopen if needed.
