### ISSUE TITLE
Use file path for setting avatar via cli client / mobile

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/go-textile#466]
**Is your feature request related to a problem? Please describe.**
Currently, `textile profile set avatar` only accepts a locally indexed image hash, this isn't very easy to do from the cli..

**Describe the solution you'd like**
It would be useful to take an actual file path.

**Describe alternatives you've considered**
Alternatives include taking a non-locally indexed hash, or easier tooling to access local file hashes. This the above proposed solution seem like the most intuitive to a dev/user.

**Additional context**
This will speed up testing, and make it easier to use cli peers for testing things like avatar display etc.

**Comment by balupton** [comment]
Was walking  through the docs to setup my local environment with some data for testing, and ran into this issue.

```
> textile profile set avatar /Users/balupton/Library/Mobile\ Documents/com\~apple\~CloudDocs/Avatars/Me/Greenspool\ -\ Square.jpg 
file not found
> textile profile set avatar "https://www.gravatar.com/avatar/9400cb5aeb155ccec614652542fd274d"
file not found
> textile profile set avatar QmeSWmeWbkyfct23sUVsBp4pqo9xmZRrcZnR6nRPgTJAVJ
file not found
```

As it seems the docs are depending on this issue already being completed:

https://docs.textile.io/a-tour-of-textile/#set-an-avatar-image

> textile profile set avatar "path/to/an/image"

**Comment by sanderpick** [comment]
Right, yeah - it’s listed under the todos in the main docs issue. I’m planning on nabbing it tomorrow.

**Comment by sanderpick** [comment]
https://github.com/textileio/docs/issues/12
