### ISSUE TITLE
Wallet overview API

### ISSUE THREAD

**Issue by asutula** [textileio/go-textile#468]
**Is your feature request related to a problem? Please describe.**
We'll need a wallet overview API to allow users to easily get information about the contents of their wallet. This would, for example, drive the Wallet drawer screen in Textile Photos.

**Describe the solution you'd like**
A method that returns a list of account objects including id, repo path, username

**Describe alternatives you've considered**
All other options involve the client traversing the filesystem, creating instances of nodes, querying information from the nodes etc, and making lots of bad assumptions about how to extract overview data. It would also involve the client manually managing different directories for different accounts. This should all just be handled in the go layer.

**Comment by sanderpick** [comment]
Thinking about this in the context of @andrewxhill's account delete PR (https://github.com/textileio/go-textile/pull/750). Here's a proposal.

Filesystem layout to match desktop:

```
<repo_path>/
    SESSION -> address_b
    address_a/repo/...
    address_b/repo/...
    address_c/repo/...
```
Where a, b, and c do not translate to wallet indexes as these addresses could be from different wallets. `SESSION` is a sort of lockfile that has a single line with the address of the "logged in" account.

High-level wallet account APIs:

- login (sets the `SESSION` file)
- logout (deletes the `SESSION` file)
- delete (delete repo and unset `SESSION` file if needed)

Prior to delete, the client _should_ auto-de-register cafes, perhaps w/ confirmation.

Thoughts?

**Comment by sanderpick** [comment]
@carsonfarmer I'm sure you thought through this stuff with desktop so feel free to chime in.

**Comment by carsonfarmer** [comment]
@sanderpick this proposal sounds great. I was going to do something much less resilient than that, where logout would just deregister cafes and kill the daemon, dropping the user back to the account selection screen. But this is really nice actually... because then, if the lockfile is present, we can just automatically load that account, which is much better than making the user select an account each time they start the tray app.
