### ISSUE TITLE
proto: can't skip unknown wire type 4 cafe_outbox

### ISSUE THREAD

**Issue by sanderpick** [textileio/go-textile#484]
Client and cafe both rc28. Fresh install.

```
11:16:06.693 ERROR   tex-core: cafe STORE request to <redacted> failed: proto: can't skip unknown wire type 4 cafe_outbox.go:199
11:16:06.696 DEBUG tex-servic: sending CAFE_STORE_THREAD to <redacted>/cafe/v0/service main.go:133
```

**Comment by doodlemania2** [comment]
This is happening on me from client when attempting to do textile cafes add.
Happening on Linux, Windows, and WSL

**Comment by sanderpick** [comment]
Hey @doodlemania2, I spent some time today on our docker container (which needed to happen anyway) in an effort to try and reproduce this on Linux. Sadly, I still cannot. Can you help me with some extra info? I know you said rc43 but just to be sure...

- What version is your cafe node running?
- What version is your local node running?

If you want to try the docker image (latest is rc45):

```
$ docker run -it -p 4001:4001 -p 8081:8081 -p 5050:5050 -p 40600:40600 -p 40601:40601 textile/go-textile
```

I need to put a little more work into that image to allow it to be used as a cafe, but you could use it as a client and then register against my dev cafe (running rc45 as well):

```
$ textile cafes add http://54.219.142.88:40601 --token <token>
```

Will DM you with my that token.

**Comment by sanderpick** [comment]
You could `docker exec -it <name> "/bin/sh"` and configure the node as a cafe as well.

**Comment by sanderpick** [comment]
Gonna close this for now. Based on our DM convo, seems to be working w/ latest versions.

**Comment by doodlemania2** [comment]
still getting proto errors in a few places...here's some logs:
server says hello:
00:02:06.421 DEBUG   tex-core: received CAFE_CHALLENGE from 12D3KooWQ7jRq96ZipeNkNf3J2Wr9d7tPmxG61vR38EFWvvyHiLh cafe_api.go:276
[GIN] 2019/02/28 - 00:02:06 | 200 |    32.65223ms |   66.68.241.178 | POST     /cafe/v0/service
00:02:06.537 DEBUG   tex-core: received CAFE_REGISTRATION from 12D3KooWQ7jRq96ZipeNkNf3J2Wr9d7tPmxG61vR38EFWvvyHiLh cafe_api.go:276
[GIN] 2019/02/28 - 00:02:06 | 200 |  160.244974ms |   66.68.241.178 | POST     /cafe/v0/service

client then says:
28 Feb 19 00:01 UTC  vvyHiLh added ANNOUNCE update to thread PyvU4Umz
proto: can't skip unknown wire type 4
appears registration worked - textile cafes ls shows "stuff"
so the bug, if it is a bug, is somewhere right after the challenge and prior to the client spitting out the registration information
in a while (dinner time now) i'll try to add some pics to a thread and see if magic happens

Also, at least one other operation is encountering proto which is textile cafes messages

**Comment by sanderpick** [comment]
Hmm, okay... reopened. What type of machine is the client on?

**Comment by doodlemania2** [comment]
Cool.
1. Windows 10 running Textile 46 in WSL mode (WSL=Ubuntu)
2. Ubuntu 18.04 running Textile 46
3. Ubuntu 16.10 running Textile 46
4. Windows 10 running Textile 46 using the Windows binary.

All sad face with proto error but registration does appear to be working. Haven't gotten to attempting to upload a file yet to see if it actually uploads to cafe - that's next!

**Comment by sanderpick** [comment]
Are these nodes brand new or have they seen some migrations?

**Comment by doodlemania2** [comment]
newbies - most of my testing, i wipe .textile each time just to be sure :)

**Comment by doodlemania2** [comment]
Just an FYI, confirmed this same error running a Cafe and a client using Docker on Linux 18.10 giving same error :(

**Comment by sanderpick** [comment]
Thanks @doodlemania2 - I'm spinning up Ubuntu now so I can reproduce. More soon.

**Comment by doodlemania2** [comment]
Okay to close! Suggest adding some sort of validation on cafe setup with the URL requiring http://andaportnumber:somethinghere

**Comment by sanderpick** [comment]
Thanks for the patience @doodlemania2 - I'll be working on a detailed cafe guide this week.
