### ISSUE TITLE
Wiki v0

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/go-textile#513]
## Description
Its time to get an initial version of the wiki 'done'. Plenty of time for future upgrades, but would be good to have an initial coverage of all core pieces done.

## Initiative / goal
This is critical for wider outside adoption. The goal here is to get a minimal set of docs/information done so that newcomers to the project can dive in and start learning about the components that make up Textile.

### Hypothesis
Full coverage of core pieces the Textile team has identified as 'core' should lead to a) additional tickets for even more coverage, b) better adoption of Textile tooling outside the core team, and c) a better medium for sharing information with outside contributors. Success is measured in the number of PRs and wiki links shared in Slack, and elsewhere!

## Acceptance criteria and must have scope
At this early stage, most submissions will be acceptable. Any coverage is better than no coverage. However, the scope will change as we move along.

## Timeline
Should be mostly done for this milestone. However, this is an ongoing Epic. It may be useful to close this one when v0 is done, and start a new one for additional/better coverage.

**Comment by andrewxhill** [comment]
Just curious if it makes sense to unify the docs with the wiki. If the output was MD you could commit the changes to a directly that github syncs with the live wiki... 

https://coderwall.com/p/3aamsa/sync-documentation-between-source-and-wiki-on-github

maybe you are already ahead of me here, just poking through what the state of a unified public docs are.

**Comment by andrewxhill** [comment]
could also start playing with a single /docs repo that pulls all these sources together
