### ISSUE TITLE
New block type: "read receipts"

### ISSUE THREAD

**Issue by sanderpick** [textileio/go-textile#524]
**Is your feature request related to a problem? Please describe.**
In convo w/ @advatar, he mentioned it would be nice to be able to know if other thread members have read a file/message. Notifications have a "read" field, but this is just for the local node's consumption.

**Describe the solution you'd like**
Add a new block type called "READ" that others can consume and be informed that the target object was read. Can function similar to an "IGNORE" in terms of its target.

**Comment by advatar** [comment]
This is also useful to mark that I have read/seen a post to be able to archive entries in the inbox

**Comment by carsonfarmer** [comment]
No longer relevant in Threads v2
