### ISSUE TITLE
Easier way to reuse schema in commandline

### ISSUE THREAD

**Issue by andrewxhill** [textileio/go-textile#550]
**Is your feature request related to a problem? Please describe.**

When creating a new thread, it would be nice to make it easier to reuse a schema from an existing thread. Maybe this exists, but in my specific case I want to 

1. Follow someone else's thread
2. Create my own thread with the exact same schema
3. `sub` the first thread, filter, and put results into my new thread.

**Describe the solution you'd like**

Either an example of how to pipe the schema result directly into the add command or a helper flag that directly does it.

e.g.

`textile schemas <thread_id> | textile addThread blah blah`

or

`textiel addThread --reuse_schema <thread_id>`

**Comment by carsonfarmer** [comment]
If we allowed the `schema` flag to take a JSON string as input, we could do something like:
```
textile threads get <thread-id> | jq -rc '.schema' | xargs -I{} textile threads add --schema={} newThread
```

Could that be enough?

**Comment by carsonfarmer** [comment]
Or even nicer, just take a schema id:

```
textile threads get <thread-id> | jq -r '.schema_id' | xargs -I{} textile threads add --schema={}
```

That seems like the right approach to me,
