### ISSUE TITLE
Threads Add

### ISSUE THREAD

**Issue by doodlemania2** [textileio/go-textile#557]
**Describe the bug**
textile threads add -t open -s invite_only gives an error on Rc48

**To Reproduce**
textile threads add -t open -s invite_only -m 12D3KooWGJkYvVbkTi31K8saGYJhPKBqU94hMuRUqwfBFiDP4SmF "Open Chat"
error parsing member: invalid version byte

**Expected behavior**
Per Wiki, create a thread.

**Screenshots**
error parsing member: invalid version byte

**Desktop (please complete the following information):**
 - OS: Linux
 - Version RC48

**Additional context**

**Comment by doodlemania2** [comment]
If i remove the -m and then add the peer later, it works!

**Comment by sanderpick** [comment]
The `-m` option takes a contact's "address", which is their wallet account address:

```
-m, --member=      A contact address. When supplied, the thread will not allow additional peers, useful for 1-1 chat/file sharing. Can be used multiple times to include multiple contacts.'
```

The reason for that is an account can have multiple devices which each have a peer ID. Note also that this _does not_ send an invite, you're just saying, "only peers from these accounts are allowed to be invited".

**Comment by sanderpick** [comment]
To see you're account address: `textile account address`

**Comment by doodlemania2** [comment]
Cool, suggest change from a tech error then to a smart error of some kind that says I didn't do the process right?

**Comment by sanderpick** [comment]
Closing this... will open another related to adding a better error.
