### ISSUE TITLE
More support for args from Stdin

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/go-textile#563]
**Is your feature request related to a problem? Please describe.**
When working with the cli tools, it is often useful to pipe output from one call into another. Something like the following to 'drop' all local threads for example:
```
textile threads ls | jq -r '.[].id' | xargs -I{} textile threads rm {}
```

but this always requires xargs in the middle to pipe outputs. This is cumbersome, and can lead to extremely complex code for something relatively simple. An 'easy' fix would be to support taking args from Stdin. An additional 'enhancement' would be to also support a `--json` flag to could take input opts as a json string.

**Describe the solution you'd like**
It is already relatively straightforward to add this to individual commands. For example, something like this will use std if no args are provided, and you'd stick this in the command's `Execute` method:
```
if len(args) == 0 {
		data, err := ioutil.ReadAll(os.Stdin)
		if err != nil {
			return someErrMessage
		}
		// could also support multiple inputs...
		arg := strings.Split(strings.TrimSpace(string(data)), " ")[0]
		args = append(args, arg)
	}
```

However, this isn't very portable, and requires a lot of code duplication. So some additional method or function to wrap this into a simpler call would be useful.

**Describe alternatives you've considered**
Not doing it is ok too... its just cumbersome and requires more steps on the 'client' end.

**Additional context**
This is mostly for testing, prototyping, and prettier code... not a blocker, just a nice-to-have!

**Comment by carsonfarmer** [comment]
Is this now more easily supported @balupton? Seems like the new CLI tooling makes this easier?

**Comment by balupton** [comment]
I think bash scripts would be sufficient and more standard approach to this, than trying to turn the CLI into something that becomes so robust, supporting all the edge cases becomes quite difficult.

The CLI should also reach a point where it shouldn't change that often, as any changes to the CLI will break things. Implementing stdin for everything seems another aspect to fragility.

The desired thing about would also be very simple with our javascript clients, something like this:

```
Promise.all(textile.threads.list().map(thread => thread.remove()).then(() => console.log('all removed'))`

**Comment by carsonfarmer** [comment]
I think that's a fair argument. Will close this as 'not needed'.
