### ISSUE TITLE
Handle multiple contacts for same account

### ISSUE THREAD

**Issue by sanderpick** [textileio/go-textile#565]
As we move toward multi-device, we'll need to start dealing with contacts from the same account. We'll want to still keep the contact object tied to a single peer, but we can roll up multiple into something consumable that contains all peers and inboxes.

**Comment by sanderpick** [comment]
I started this a couple days ago and realized it's a little more involved than I first thought. Here's the problem: 

A `Contact` is associated with a peer ID, which is fine, we need (at least for now) to talk directly with other peers, not accounts. However, a user should not need to deal with multiple contacts for the same account address.

My proposal: wrap contacts with a `ContactCard` object that is just a map of peer ID -> `Contact`:

```
message AccountCard {
    map<string, Contact> contacts = 1;
}
```

or maybe just `Card`? Thoughts @asutula? I would have liked to have dealt w/ this sooner, but there have been too many moving pieces.

**Comment by asutula** [comment]
Sounds reasonable to me. Do you imagine any user of the Textile tools/SDK will ever need to access and use the individual `Contact` objects for any reason?

**Comment by sanderpick** [comment]
I _think_ the tools would still have to interact w/ the individual contacts to render username and avatar. Another approach here would be to just mash together the contacts to essentially create the "best" contact, which contains the most recently updated username and avatar. This could only be for display purposes though because search results and the contact add API still need to deal with single `Contact`s.

Given that we already have a model like this for `Contact` and `User`...

```
message Contact {
    string id                         = 1;
    string address                    = 2;
    string name                       = 3;
    string avatar                     = 4;
    repeated Cafe inboxes             = 5;
    google.protobuf.Timestamp created = 6;
    google.protobuf.Timestamp updated = 7;

    // view info
    repeated string threads = 8;
}

message ContactList {
    repeated Contact items = 1;
}

message User {
    string address  = 1;
    string name     = 2;
    string avatar   = 3;
}
```

Maybe something like this is better:

```
message Card {
    User user            = 1;
    ContactList contacts = 2;
}
```

This way, it's more consumable by the SDKs/UIs since it deals w/ `User`s like the Feed API, but can also be used by the the Contacts API w/ some tweaks to the search results and the add method.

**Comment by asutula** [comment]
Sounds like a good compromise. I'm definitely for simplifying the API. Dealing with individual `Contact`s and having developers decide what logic to apply isn't the way to go.

**Comment by sanderpick** [comment]
I started with the above model and after playing around with it via the command line, I realized it's pretty confusing. Like, what's a `Card`? Why does it have a `User` and `Contacts`?, What are those, etc...

I landed on migrating `Contact` to `Peer` since this object maps directly to a single IPFS peer... and then a new `Contact` object that wraps peers and has the same display at a `User` object (used in the feed):

```
message Peer {
    string id                         = 1;
    string address                    = 2;
    string name                       = 3;
    string avatar                     = 4;
    repeated Cafe inboxes             = 5;
    google.protobuf.Timestamp created = 6;
    google.protobuf.Timestamp updated = 7;
}

message PeerList {
    repeated Peer items = 1;
}

message User {
    string address = 1;
    string name    = 2;
    string avatar  = 3;
}

message Contact {
    string address      = 1;
    string name         = 2;
    string avatar       = 3;
    repeated Peer peers = 4;
    repeated string threads = 5;
}

message ContactList {
    repeated Contact items = 1;
}
```

Note that only `Peer`s are actually indexed / stored.

Here's a `Contact`:
```
{
    "address": "P47FEZnTdDEexCU8PcUU9KLjMSWgQjJEeYR6wTinJRsEGWoK",
    "avatar": "QmV8eY9TXrJy66r5ScLTawbqKfkT7UppT9cnYDcVN3E1s5",
    "name": "andrew-beta",
    "peers": [
        {
            "address": "P47FEZnTdDEexCU8PcUU9KLjMSWgQjJEeYR6wTinJRsEGWoK",
            "avatar": "QmV8eY9TXrJy66r5ScLTawbqKfkT7UppT9cnYDcVN3E1s5",
            "created": "2019-02-06T00:32:48.733088Z",
            "id": "12D3KooWQAy5QRnCCd6Rz86CS7hzS7WMAEFEXxmbkofWtkyxAG6R",
            "inboxes": [
                {
                    "address": "P5Mm4xsek1jP8VkijzKYu2G1XNRogbFEiraRW5rqqgYzv7Ag",
                    "api": "v0",
                    "node": "1.0.0-rc30",
                    "peer": "12D3KooWLh9Gd4C3knv4XqCyCuaNddfEoSLXgekVJzRyC5vsjv5d",
                    "protocol": "/textile/cafe/1.0.0",
                    "swarm": [
                        "/ip4/18.224.173.65/tcp/4001"
                    ],
                    "url": "https://us-east-2b.textile.cafe"
                },
                {
                    "address": "P5LeaXjN7souJTxSJzB77Grs5ZQdy64UZxZt2rrQ2aHzyfU9",
                    "api": "v0",
                    "node": "1.0.0-rc30",
                    "peer": "12D3KooWGBW3LfzypK3zgV4QxdPyUm3aEuwBDMKRRpCPm9FrJvar",
                    "protocol": "/textile/cafe/1.0.0",
                    "swarm": [
                        "/ip4/18.144.12.135/tcp/4001"
                    ],
                    "url": "https://us-west-1a.textile.cafe"
                }
            ],
            "name": "andrew-beta",
            "updated": "2019-02-06T00:32:48.733088Z"
        }
    ],
    "threads": [
        "12D3KooWAmQan7rTFtnGNSeFVARAfRT5Fw5YbA9R66JmHK53dBC7",
        "12D3KooWSaF74rhqDwNZpBKK8RqnRMa2wj7AwyAzUhVo2YYF28rK"
    ]
}
```

Note that `threads` (shared thread IDs) are part of the new `Contact` object, not `Peer` (the old `Contact`), this way, the meaning spans all of the contact's known peers.
