### ISSUE TITLE
Thread members don't get updates via Cafe

### ISSUE THREAD

**Issue by andrewxhill** [textileio/go-textile#571]
This has been happening for > 1 month. Members of my family group cease to get updates on that thread (or any other) and never seem to update via the cafe alone.

On Justine's device, I've tried to poke around and see what's happening. What I found was that 

Scenario 1: Normal usage

I could post photos from my device on any group we are both part of; or, send an invite to a new thread. Her phone never gets those updates and just consistently displays her post from weeks ago.

Scenario 2: Forced p2p

I could open her Textile Photos app and my Textile Photos app side by side. If I then performed an action in any shared group (e.g. like a photo), her phone will get that p2p update and then perform the steps necessary to fill in the history.

Conclusion:

It seems that the p2p updates are working well but she doesn't get any over the cafe anymore. I've confirmed that the same is happening to other members of my family group. 

I dumped what logs I could get last week and just saw those endless merges but then nothing for a long time. Let me know what else I can try to report from her phone.

**Comment by sanderpick** [comment]
Couple questions:
- Are they on very latest public release? That should stop those logs about failed message checking. 
- Does this happen w/ new threads or just an old one?

Without any other logs / errors, I'd say the next step would be to sit down with her phone and do some debugging against the prod cafes.

**Comment by sanderpick** [comment]
This was a result of a bug where duplicate inbox messages caused none of them to be handled. Closing.
