### ISSUE TITLE
Missing Files annotations in feed api

### ISSUE THREAD

**Issue by asutula** [textileio/go-textile#603]
90% sure that `FeedItem`s that are `Files` are coming back with empty likes and comments. It seems that the comments (and probably likes too) are coming back fine in the normal `files` api.

**Comment by sanderpick** [comment]
Will take a look ASAP

**Comment by sanderpick** [comment]
Looking...

**Comment by sanderpick** [comment]
@asutula what `FeedMode` are you requesting?

**Comment by asutula** [comment]
CHRONO

**Comment by sanderpick** [comment]
`CHRONO` doesn't nest the annotations. They appear in pure chronological order. `ANNOTATED` will nest them, and `STACKS` nests them unless there's a break in continuity, in which case they would appear as in `CHRONO` with the target nested (flipped).

**Comment by asutula** [comment]
:face_palm::skin-tone-2:
