### ISSUE TITLE
Pin all schema files locally until "released"

### ISSUE THREAD

**Issue by sanderpick** [textileio/go-textile#638]
Related to #637

**Comment by asutula** [comment]
Just thinking more about the data model related to this...

Would be great to have a property of `Files` or `File` that is some sort of remote pin "status". Maybe it's just a boolean or maybe it's a list of cafes that have the data pinned or something. 

I'm thinking a big part of our UI/UX should be about displaying this status for any data that is added to Textile.

**Comment by sanderpick** [comment]
We've spoken about this before. It's covered by the cafe requests themselves w/ a negative space approach vs. adding additional (redundant) data. If there are _no_ pending requests for a particular file, it has been synced to the available cafes. The cafes themselves will keep a record of the pin at the hash level.

**Comment by asutula** [comment]
Hmm yea I remember that now.

Trying to poke a hole in that logic... 

What if I have no registered cafes? In that case, in order to know if a file is synced, I need to know there are no pending cafe requests for it AND that I have at least one cafe registered.

What about the case where I receive a file over p2p with an account peer? Maybe that peer has cafes registered and pinned the file to a cafe, maybe not. I have no way of knowing. 

If I get a file from my cafe inbox, I can assume that the file exists on that cafe, but is there even a way to know if a file came from a cafe inbox vs p2p?

(definitely overstepping my knowledge of cafes and p2p in Textile here, please correct me)

**Comment by sanderpick** [comment]
> What if I have no registered cafes? In that case, in order to know if a file is synced, I need to know there are no pending cafe requests for it AND that I have at least one cafe registered.

We can expose an API or add a param to `FeedItem`s that conveys this info. I'm just saying to underlying determination can be done w/o tracking additional info. The problem is that adding a new table for this info becomes very complex since we would need to track all the nodes as well as meta/content links. I had a couple full days of brain spinning on this exact topic.

> What about the case where I receive a file over p2p with an account peer? Maybe that peer has cafes registered and pinned the file to a cafe, maybe not. I have no way of knowing.

Right, cafes are at the peer level. Not account level. That's a separate issue that needs to be solved. One proposal is to share cafe info via the account thread. The pin state of a file/node will be kept on the cafe in a single place and query-able... there's no need to distribute that state.

> If I get a file from my cafe inbox, I can assume that the file exists on that cafe, but is there even a way to know if a file came from a cafe inbox vs p2p?

The inbox messages don't contain files. The messages are encrypted blocks. Once downloaded and decrypted, they are processed in the same way as if they came directly from a peer. If you send me a block pointing to a file at _my_ inbox, I can_not_ assume you have that file pinned on the same cafe. That storage state would need to recorded separately, even if we shared the same cafe.

**Comment by asutula** [comment]
Cool thanks for the explanation. Some of it's a little over my head, but I do believe you understand it and the data will be available to me.

**Comment by sanderpick** [comment]
Yeah, of course. At the very least, I think this less-work approach makes enough sense to give it a go.

**Comment by sanderpick** [comment]
This convo is probably more relevant to the File Sync epic. This issues is no longer needed since the cafe requests will be written to disk (we don't need to get the data from the repo).
