### ISSUE TITLE
Tray: Design + Implement Screens

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/go-textile#643]
Currently, we are pushing to make the tray app the primary interface for account management on desktop (for now?). There are several user stories that go along with this, and several key screens that will have to be developed. This ticket is for tracking screen development.

**Minimal screen requirements**
- [x] Welcome screens with information, similar to mobile on-boarding screens
- [x] Screen to present mnemonic phrase.
    - Should include option to input existing mnemonic.
    - Should also include password field.
    - Should include option to (re)generate mnemonic
- [x] Information screens (or messages) upon 'login'
    - Feedback for user as app searches network for existing backups.
    - Should probably only automatically search for the first 3 (?) accounts
    - Present option to 'check for' additional accounts
    - Creating additional accounts will also be required, but will scoped to #622 
- [x] Login/logout screens
    - Could be (re)useable for the above mnemonic phrase input screen

**State of the art?**
There are several existing apps and services that have already explored some of these flows. The obvious ones include Blockstack, Keybase. More will be added as they are explored, testing, and evaluated. Ideally, there is a way to present the complex information flow to those who want it, while reducing exposure for those who just want to get going quickly.

**Comment by carsonfarmer** [comment]
Here's an initial tray app screen design courtesy of `@shokunin` on slack (https://slack.textile.io)
![mockup](https://user-images.githubusercontent.com/1220613/54711520-5dad3f00-4b07-11e9-8e65-bfa11df57dae.png)

**Comment by sanderpick** [comment]
Coolio. Will need some explanation w/ this. What are the boxes?

**Comment by carsonfarmer** [comment]
More to come, so I'll save the explanations until there's more context. But the tl;dr here is that this is for further down the road when we have our 'app' launcher going (so those boxes are apps, contact management, backup folder, photos, notes, etc). For now, the top bar is what we're focused on, which requires additional screens to be useful.

**Comment by sanderpick** [comment]
Sweet, sounds good.

**Comment by carsonfarmer** [comment]
Initial work here done with #673
