### ISSUE TITLE
Tray: Safely store a user's mnemonic on device

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/go-textile#644]
**This would be nice from a UX perspective** but has to be done right, safely, and clearly. Important to research how others have done this. The _where_ to store part is easy, the _how_ (using the default PBKDF2 password salt, more serious encryption, etc) is less obvious.

**Comment by asutula** [comment]
I think we just use the OS provided utilities for secure token storage. In iOS, this would be Keychain which is encrypted and protected by passcode/biometric access.

**Comment by asutula** [comment]
There's probably an equivalent on Android. I guess this is an SDK level thing.

**Comment by sanderpick** [comment]
I think this would be Tray-only right? via a key-val store in the sqlite db

**Comment by carsonfarmer** [comment]
Yes. Just tray. Should probably prefix tray with with ‘tray’ to keep it clearer.

**Comment by carsonfarmer** [comment]
After some offline discussion with @sanderpick. I think we've settled on using AES-256-CBC with a SHA512 HMAC tacked on to encrypt and store a bip39 mnemonic. We'll also be encrypting the individual datastores using the github.com/mutecomm/go-sqlcipher self-contained sqlite3 driver. This uses PBKDF2-HMAC-SHA512 (256,000 iters) to derive a key from an input password, and then the entire db is encrypted using 256-bit AES in CBC mode (same as our mnemonic). It also uses HMACs on page writes etc. We'll be using the following 'directory' structure in the `Application Support` folder:

```
Textile/
├── account0/
│   └── repo/
├── account1/
│   └── repo/
...
├── accountN/
│   └──repo/
└── wallet.info
```
