### ISSUE TITLE
Stand alone JS/TS types package please

### ISSUE THREAD

**Issue by asutula** [textileio/go-textile#666]
**Is your feature request related to a problem? Please describe.**
We are currently only publishing the TS/JS generated types as part of the go-mobile package which includes the framework and aar.

**Describe the solution you'd like**
We need to publish the JS/TS types as a stand alone module because the framework/aar won't be needed anymore from npm once we migrate the RN sdk to just use ios-textile and android-textile (which pull in the framework/aar via cocoapods/gradle)

**Describe alternatives you've considered**
none

**Additional context**
We can probably stop publishing go-mobile once this happens.

**Comment by carsonfarmer** [comment]
I wonder if we can have a 'unified' types package with the JSON -> Typescript types as well?

**Comment by asutula** [comment]
I manually published this for now to keep things moving on the sdk front. Here is the `package.json` I used that we can base the automated release on:
```
{
  "name": "@textile/js-textile-types",
  "description": "Protobuf generated Javascript types for Textile",
  "version": "0.1.11",
  "author": "textile.io",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/textileio/go-textile"
  },
  "bugs": {
    "url": "https://github.com/textileio/go-textile"
  },
  "homepage": "https://www.textile.io/",
  "keywords": [
    "encrypted",
    "decentralized",
    "ipfs",
    "libp2p",
    "golang",
    "macos",
    "linux",
    "windows",
    "ios",
    "android"
  ],
  "files": [
    "dist"
  ],
  "main": "dist/index.js",
  "types": "dist/index.d.ts",
  "dependencies": {
    "protobufjs": "^6.8.8"
  }
}
```

**Comment by asutula** [comment]
Updated the package name to `@textile/js-types`.

**Comment by carsonfarmer** [comment]
Can we close this one @asutula? Now that #751 has landed?
