### ISSUE TITLE
Get raw file from block id

### ISSUE THREAD

**Issue by andrewxhill** [textileio/go-textile#688]
After adding a file with the CLI you get the block id response.

Without having to look at that block and parse out the files, is there a way to get the raw file back?

for example, using the block id `QmWWasyab1KB2xVPYHUtYxHNEa6PjD24w1cjSu8tfn4mMm`

`textile files get QmWWasyab1KB2xVPYHUtYxHNEa6PjD24w1cjSu8tfn4mMm` 

will just return the block. is there a trick the following that i'm missing?

`textile files get QmWWasyab1KB2xVPYHUtYxHNEa6PjD24w1cjSu8tfn4mMm/0`

**Comment by sanderpick** [comment]
`Block.Target` points to the DAG contains the file(s)... maybe a helper method could be useful?

```
textile blocks data {Block.Id} --path /0/large
```

That would just cat the data at `target/0/large/d`.

**Comment by andrewxhill** [comment]
yeah, that would be perf

**Comment by balupton** [comment]
Okay, accomplished this with the following bash script.

``` bash
#!/usr/bin/env bash
set -Eeuo pipefail

blockid="${1:?"USAGE: get-block-contents.bash <BLOCK-ID> <LINK-NAME>"}"
linkname="${2:?"USAGE: get-block-contents.bash <block-id> <LINK-NAME>"}"

blockdata="$(textile files get "$blockid")"
linkdata="$(echo "$blockdata" | json "files[0].links.$linkname")"
linkhash="$(echo "$linkdata" | json "hash")"
linkkey="$(echo "$linkdata" | json "key")"

textile ipfs cat "$linkhash" --key="$linkkey"
```

However, is there a way to get the block to output its files in the `textile files keys <targetid>` format? Which is the `/0/X` style, as `textile blocks get` outputs in a `files[].links.X` style.

**Comment by sanderpick** [comment]
Nice @balupton. Does trentm have advantages over `jq`? 

In the JSON form, we just assume the indexes are implied by the objects' array position.

The idea here is to add an additional command `textile blocks data {Block.Id} --path /0/large` with a corresponding API (`GET`->`/blocks/:id/content`?) handler that can accomplish this in one round-trip.

**Comment by sanderpick** [comment]
In light of the planned link changes, we may as well add an additional handler for `meta`. We could also explicitly state the index like,

- `textile blocks meta {Block.Id} --index 0 --path /large` -> `GET /blocks/:id/meta`
- `textile blocks content {Block.Id} --index 0 --path /large` -> `GET /blocks/:id/content`

`--path` could go deep into a directory. So, can remain flex. No `--path` would just mean that we're dealing with a single node (no links).

**Comment by balupton** [comment]
What exactly would `GET /blocks/:id/content` return? I wonder this, because the block doesn't have any file content, only its files do, in which case, what file should be the default if no path was specified?

> I wonder this, because the block doesn't have any file content,

This was surprising to me. I had thought that textile would upload the original image file to its database, but it seems to only upload the processed/resized images to its database.

Seems a consolidated API like this would be the way to go:

- `/block/:blockid/meta`
- `/block/:blockid/content`
- `/block:blockid/files/0/large/meta`
- `/block:blockid/files/0/large/content` redirects to `/file/:fileid/data`
  - `/file/:fileid/data` should probably be renamed to `/file/:fileid/content`, and have`/file/:fileid/meta` added

If the `/meta` suffix is omitted, the metadata is also returned.

**Comment by sanderpick** [comment]
If no path, then no content would be returned (bad request). The API can’t make assumptions about the schema.

**Comment by sanderpick** [comment]
Ah, had to read that again. I see what you mean. So, I think we're saying the same... it's just that the path can be added to the URL.

Some tweaks for consistency:

- `/blocks/:id/files/<index>/<path>/meta` (`blocks` plural, `:id` not `:blockid`, the block part is implied)
- `/blocks/:id/files/<index>/<path>/content` (if you're going to redirect, may as well redirect the above route as well)

**Comment by sanderpick** [comment]
So, no <index>/<path> would result in a 404. No /meta or /content also 404.

**Comment by balupton** [comment]
Ok. The reason I mentioned redirecting, is currently `/blocks/:id` returns the metadata for the block, so a redirect would be a graceful upgrade, whereas a 404 would be a b/c break.

**Comment by balupton** [comment]
So proposal is:

- `/blocks/:id/` redirects to `/blocks/:id/meta ` for b/c
- `/blocks/:id/meta` returns metadata for the block
- `/blocks/:id/content` returns decrypted content for the block
- `/blocks/:id/files/<index>/<path>/meta` returns the metadata for the path at the block
- `/blocks/:id/files/<index>/<path>/content` returns the decrypted content for the path at the block, and would transparently redirect to `/file/:id/data` to fulfil the request

**Comment by sanderpick** [comment]
Nice, I like it 👌🏼. I was confusing your block meta for file meta.

**Comment by balupton** [comment]
Trying to figure out how to do this:

> * [ ]  `/blocks/:id/content` returns decrypted content for the block

And now I understand what you mean by this:

> If no path, then no content would be returned (bad request). The API can’t make assumptions about the schema.

Is there any examples of when a block has content? As a block's content is its JSON encrypted data right? It is only files that have metadata, and content. Or perhaps I have misunderstood something.

**Comment by sanderpick** [comment]
I think it's ok how you propose. We just need the handler to take a * path after the `files` fragment and before the `meta` and `content` fragments. Then, you'd need to cat the data for both endpoints via `DataAtPath` which can take the block's target + the full path after `files`. Writing this quick before hitting the sack here. Can help more tomorrow / when you're back.

**Comment by balupton** [comment]
Not a problem. Just wanted to clear up that one point. Already on my way implementing this :)

**Comment by balupton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [⅞ 🍅 Get raw file from block id #688](https://trello.com/c/qbDrEpRK/9-%E2%85%9E-%F0%9F%8D%85-get-raw-file-from-block-id-688)

**Comment by balupton** [comment]
Released to https://github.com/textileio/go-textile/releases/tag/v0.2.0
