### ISSUE TITLE
Add CORS support to gateways

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/go-textile#692]
We now have outside developers using our decrypting gateways to fetch data on behalf of users. While this isn't ideal, for now it is the best course of action when building pure browser apps on top of Textile data. To support such usage, we need to add CORS support so that web-apps can `fetch` data via the gateways.
We already have nice CORS support for the REST APIs, so there is a working example to base this work off. For the gateways, things can probably be even simpler, because we can just open up to all domains, which I think is the default for the CORS lib we're using.

**Comment by balupton** [comment]
Ok got this going locally and verified with tests as well as:

``` js
fetch('http://127.0.0.1:5050/health').then(console.log).catch(console.error)
```

@carsonfarmer should the gateway CORS config be configurable by the user at all?

**Comment by carsonfarmer** [comment]
Good question. I think maybe yes? But with open defaults? Our API config let's you configure. I could imagine someone wanting to limit gateway CORS access in certain contexts.

**Comment by balupton** [comment]
Ok, will do

**Comment by balupton** [comment]
Which of these from the API config are relevant to the Gateway?

``` go
"Access-Control-Allow-Methods": {
   "GET",
   "POST",
   "DELETE",
   "OPTIONS",
},
"Access-Control-Allow-Headers": {
   "Content-Type",
   "Method",
   "X-Textile-Args",
   "X-Textile-Opts",
   "X-Requested-With",
},
```

**Comment by carsonfarmer** [comment]
Yeh I think probs the default headers are sufficient for anything the gateway will serve, and actually, gateway only really needs to support `GET` I think... so maybe just defaults all around? In other words, leave them blank and config, and only use them if a user changes them?

**Comment by balupton** [comment]
For the headers for the gateway, omitting headers config will use these defaults:

```
"Origin",
"Accept",
"Content-Type",
"X-Requested-With",
```

Shall I just do `"*"` to allow all headers?

**Comment by carsonfarmer** [comment]
Yeh I think so. I don't _think_ we react to anything special anyway, so no probs there I think.
