### ISSUE TITLE
Role-based thread access control

### ISSUE THREAD

**Issue by sanderpick** [textileio/go-textile#694]
The current model based on thread type and sharing settings is over-engineered and confusing. This design was largely based on the idea of an immutable member "whitelist". Only the addresses in the whitelist are allowed to join, _ever_. This is a little superficial though in a way… and is the reason for the current complexity.

Roll-based access, like that seen in Google Docs, etc. is much more familiar to internet users. Something like this graph (thanks to @leshokunin):

![image (1).png](https://images.zenhubusercontent.com/5c2e879a4feb4829c013530c/64c95325-233e-4861-b3b3-3b39b7e06af0)

In practice, this means throwing out `Type` and `Sharing`, and re-purposing `Members`. When creating a thread, you’d just need to define the “star” (`*`) member’s roll (admin, write, view+comment, view, or no access). The assumption here is that an admin/owner can invite others, no matter what.

We should consider another capability around "view history". The thread purpose dictates whether or not new members ought to have the ability to view history or not. For example, most would agree a chat thread should not grant view history, but a photo album should. However, unless we leveraged the double-racket algorithm., not sure how this could truly be enforced. 

Questions:

Is there a place for voting to ban or remove content? Banning will have to come from key rotation. Essentially, we'd have to enable thread forking... plant the old key in the chain for backward traversal, and then use a new key going forward.

**Comment by leshokunin** [comment]
How about having the voting in the comment thread?

**Comment by sanderpick** [comment]
Seems like you'd want to do something like "propose" an action that could be voted on with an additional block type... that could look very much like a comment, but carries an explicit meaning.

**Comment by sanderpick** [comment]
(Also, apologies for the delay in getting this issue written up!)

**Comment by leshokunin** [comment]
Agreed. I think the thread is a good place for those things. One thing in the Epona designs I've been considering is having the ability to react to things. For example replying to a comment, or liking a comment. I would imaging voting would be similar.

**Comment by sanderpick** [comment]
Yep, exactly. You _can_ currently "annotate" (like / comment) any other block type.

**Comment by leshokunin** [comment]
So you can like a comment?

**Comment by carsonfarmer** [comment]
Yessir!

**Comment by sanderpick** [comment]
From a convo with @andrewxhill this morning, let's think deeper around how to include apps in this framework beyond the current unique thread key string.

**Comment by leshokunin** [comment]
That would be great. What kind of issues do you have in mind?
I’d love to make sure I can access the same things from all my devices and
perform the same actions with the same account.

**Comment by andrewxhill** [comment]
illustrative use-case I had in mind:

Someone tweeted that they wanted photo support in Notes app. One way to do that would be to create a second Media thread in the Notes App. That Media thread should also be permissioned to the Photos app…  so your Photos notes are part of your unified galleries in a way. Up to the user to do that permissioning, but once they do, both apps would have access to the single thread. 

Not that we will do this, it's just a nice clean example.

**Comment by leshokunin** [comment]
I’d “nope” out real fast of a system like this. Sounds like I’d be limited
from building custom things on top of Textile, and would be beholden to
some standard. I’d think of my apps as just clients, renderers for that
content. It sounds really heavy handed to me.

I’d prefer if there was a general API for actions on items, so if someone
wanted to query Notes from the Photo app, they could, so long as they auth
properly and prose the content the way it was done (assuming the people who
did the notes and photos apps documented how they do it).

**Comment by andrewxhill** [comment]
I think you are reading it wrong. It's in-line with your second thought.

**Comment by leshokunin** [comment]
Great!
