### ISSUE TITLE
Stuck on loading screen after entering wrong password

### ISSUE THREAD

**Issue by lilyrae** [textileio/go-textile#710]
**Describe the bug**
When I open the tray app and try to login to my account with the wrong password, I get stuck with a loading screen and no obvious way to restart the app and enter the correct password.

**To Reproduce**

1. Open the Textile Tray app
2. Enter an incorrect password
3. Click sign in
4. See Textile logo (loading screen?). You cannot navigate away.

**Expected behavior**
Authentication should fail, an error message should be shown and the user should be returned to the login page.

**Tray app (please complete the following information):**

-   OS: Ubuntu 16.04
-   Version: Textile_v0.1.12-rc1_linux-amd64

**Comment by sanderpick** [comment]
Issue moved to [textileio/desktop #21](https://github.com/textileio/desktop/issues/21) via [**ZenHub**](https://www.zenhub.com/)

**Comment by sanderpick** [comment]
Thanks for the report! I moved this over to https://github.com/textileio/desktop/issues/21.
