### ISSUE TITLE
Incorrect result from Cafes.session()

### ISSUE THREAD

**Issue by asutula** [textileio/go-textile#724]
**Describe the bug**
`Cafes.session(peerId)` returns nil and no error for unknown `peerId`

**To Reproduce**
Call it with a bogus peerId

**Expected behavior**
Other methods we have that take in an identifier and possibly return a result return an error if there is no record found associated with the specified id. That is nice. It should work like that.

**Comment by asutula** [comment]
Same with `refreshSession()`

**Comment by sanderpick** [comment]
What's the benefit of erorring here? `nil` is telling you it doesn't exist.

**Comment by asutula** [comment]
I'm just trying to find some consistency between similar methods in other parts of the api.

**Comment by sanderpick** [comment]
I thought we said, if it really _should_ be there, we can error, like an account thread, own contact, profile, etc. We'd be in a bad state without those. There no way for the lib to know if we _should_ have this cafe session or not.

**Comment by asutula** [comment]
What I'm seeing is that `Contacs.get(id)` and `Threads.get(id)` return errors if you pass in an id for an unknown record. I don't see how `CafeSessions.get(id)` is any different. I'm just suggesting that maybe they should work consistently. Or I need to understand the reasons for how `CafeSessions.get(id)`  should be different.

**Comment by asutula** [comment]
By "similar methods in other parts of the api" above, I meant those, `Contacs.get(id)` and `Threads.get(id)`.

**Comment by sanderpick** [comment]
Ok, so based on the rules those should not error and I we can fix those.

**Comment by asutula** [comment]
Sounds good to me. I think that makes more sense than erroring out for a condition that is pretty normal.

**Comment by sanderpick** [comment]
Ok, sweet.

**Comment by asutula** [comment]
Closing this in favor of https://github.com/textileio/go-textile/issues/725
