### ISSUE TITLE
Contacs.get(id) and Threads.get(id) should not error for unknown id

### ISSUE THREAD

**Issue by asutula** [textileio/go-textile#725]
**Describe the bug**
Currently they return errors if you pass in an unknown id.

**To Reproduce**
Pass in an unknown id

**Expected behavior**
They should return `nil` similar to `CafeSessions.get(id)`

**Comment by asutula** [comment]
Looks like possibly `Files.data`, `Files.imageDataForMinWidth` and `Ipfs.dataAtPath` also currently return errors for data not found. If that seems like it should just return nil, let's make the changes there too.

**Comment by sanderpick** [comment]
Cool, will do
