### ISSUE TITLE
Add PUT and PATCH options to default API Access-Control-Allow-Methods

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/go-textile#744]
Getting some CORS errors from the api client when performing contact search and add.

**Comment by balupton** [comment]
@carsonfarmer there doesn't seem any downside to enabling this for all, so seems we can future proof this by just enabling all of them:

```
http.MethodConnect,
http.MethodDelete,
http.MethodGet,
http.MethodHead,
http.MethodOptions,
http.MethodPatch,
http.MethodPost,
http.MethodPut,
http.MethodTrace,
```

**Comment by carsonfarmer** [comment]
Yeh good call... "collect em all"!
