### ISSUE TITLE
Include NPM in go-textile docker image

### ISSUE THREAD

**Issue by andrewxhill** [textileio/go-textile#771]
I'm looking to run the js playground as a set of integration tests. 

here is the CircleCI job

https://github.com/textileio/js-http-playground/pull/4/files#diff-1d37e48f9ceff6d8030570cd36286a61R21

The issue is that 

1. the docker image doesn't have NPM available
2. the user doesn't seem to have the ability to setup any new tools

Wondering if we can broaden up either the official image or publish a secondary image that would make the above job possible.

**Comment by sanderpick** [comment]
You mean the image used for building, not the `textile` daemon image, right?

**Comment by andrewxhill** [comment]
I mean the daemon, or an alternate version of it for integration tests. Otherwise, I'll need to pull and build go-textile on ever integration test. maybe that has to happen anyway with docker though?

**Comment by carsonfarmer** [comment]
Closing as no longer relevant.
