### ISSUE TITLE
Unexpected feed stack behavior

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/go-textile#778]
I’ve been working with the feed api in stacks mode on desktop, and when using with real data, seems to lead to some unexpected behavior in some cases. 
The main thing is updates with a ‘target’ (say a like), can end up in the main feed. Great. But then they are _not_ shown with the their target. This is ok, unless you are having a ‘threaded’ conversation in comments. Which can lead to parts of the conversation ending up in different parts of the feed. Perhaps a hybrid option is possible?
I’ll try to produce a screenshot to better illustrate the issue.

**Comment by sanderpick** [comment]
This is expected - perhaps not desirable. The nesting will differ depending on the stack alignment. The `like` is meant to only show in one place. Stack building: https://github.com/textileio/go-textile/blob/master/core/feed.go#L84

For the threaded conversations, would it make more sense to get a feed of chronological annotations (comments + likes)? As in, make one of these for comments and likes: https://github.com/textileio/go-textile/blob/master/core/feed_comments.go#L9

The full threaded convo will take a little more work. For example, a file can't have a parent like a comment/like can.

**Comment by carsonfarmer** [comment]
Closing this in favor of discussion over here: https://github.com/textileio/docs/issues/77
