### ISSUE TITLE
Daemon doesn’t shutdown cleanly when open broadcasters still running

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/go-textile#779]
This happens when (say) there are open subscriptions to thread updates. The fix is likely to to send a 'kill' call to any open broadcasters on shutdown. Since we know they’ll never be written to again, we should be able to just blindly close all open broadcasters?

**Comment by balupton** [comment]
Upon receiving a second `SIGINT` we should output whatever is causing the hold up.

**Comment by sanderpick** [comment]
hrm, never mind... I just saw it without that error.

**Comment by carsonfarmer** [comment]
Close as stale, moving on to Threads v2 daemon.
