### ISSUE TITLE
textile cafe messages

### ISSUE THREAD

**Issue by doodlemania2** [textileio/go-textile#793]
**Describe the bug**
command `textile cafe messages` returns "cafe not found" - not taking second argument?

**To Reproduce**

Add a cafe
Run textile cafe messages
See error

**Expected behavior**
Response from API as described in cli

**Additional context**
0.2.2

**Comment by balupton** [comment]
/cc @sanderpick 

My suspicion for this is that the daemon isn't configured yet for communication with any particular cafe. As I get the same, but I never did the cafe walkthrough in the tutorial.

**Comment by carsonfarmer** [comment]
That command shouldn't require a connection to a cafe per se.

**Comment by sanderpick** [comment]
Looks like it's hitting the get cafe endpoint (the `GET` means it looks for a cafe with id "messages")

```
func CafeMessages() error {
	res, err := executeStringCmd(http.MethodGet, "cafes/messages", params{})
	if err != nil {
		return err
	}
	output(res)
	return nil
}
```

**Comment by sanderpick** [comment]
(Should be a POST)
