### ISSUE TITLE
textile files add from Tour Docs

### ISSUE THREAD

**Issue by doodlemania2** [textileio/go-textile#794]
**Describe the bug**
Tour document: https://docs.textile.io/a-tour-of-textile/#add-some-data returns:
Textile error: required argument 'path' not provided.

**To Reproduce**

```
echo "mmm, bytes..." | textile files add --thread="threadid"
```

**Expected behavior**
Bytes added per docs.

**Additional context**
v0.2.2

**Comment by balupton** [comment]
fix will be pushed up later today
