### ISSUE TITLE
CLI: `textile --help` should just provide help overview, rather than all commands

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/go-textile#798]
It would be useful (and similar to other cli tools) to simply print a help overview (just a list of possible sub-commands to request help on) rather than printing out short descriptions of all the commands. This list is quite long.

Ideally the UX is: `textile --help` to figure out what I can ask help on, and then `textile <sub-command> --help` to get specific help. Maybe `textile --help-long` would be good for this longer output?

**Comment by balupton** [comment]
Is the desire for this conformity?

Personally, I find this really useful, as I can browse all the possible descriptions, then delve deeper on them. If the descriptions are omitted, then I have to help each one manually to find out more about them.

**Comment by carsonfarmer** [comment]
The request is mostly UX based I think. Given this is run from a cli, the long descriptions tend to require scrolling back and forth to find what you're looking for. A more concise display would require this less. I'm thinking in particular on remote terminals or less gui-driven cli interfaces in particular.

**Comment by balupton** [comment]
I think in those environments, the user already knows what they are intending to run

**Comment by balupton** [comment]
Ended up agreeing with you. Now using the the kingpin compact output by default. Not as compact as `nom --help` but good enough.

**Comment by carsonfarmer** [comment]
Agree, still pretty long, but _much_ improved IMHO.
