### ISSUE TITLE
Q: is having `subscribe` command versus `threads unsubscribe` confusing?

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/go-textile#799]
These are very different things (subscribe is more of a developer API for subscribing to events), and the `threads add` command doesn't really fit with unsubscribe? What about `threads leave (or remove)`? Maybe `subscribe` should be renamed to something like `listen` or `stream`?

**Comment by balupton** [comment]
I'm down. However this seems @sanderpick's call.

**Comment by sanderpick** [comment]
`leave` feels most appropriate to me

**Comment by balupton** [comment]
How about `abandon`, as that encompasses the leave plus remove dynamic.

**Comment by carsonfarmer** [comment]
I vote for `leave` as well. It still has the same idea (you area leaving the party... if there's no one left at the party, it ceases to be a party), while being a more commonly used term.
