### ISSUE TITLE
Can't run `textile wallet accounts` any more

### ISSUE THREAD

**Issue by flyskywhy** [textileio/go-textile#809]
**Describe the bug**
Can't run `textile wallet accounts` any more with version 0.2.2 and 0.2.3

**To Reproduce**

1. Download go-textile_v0.2.3_linux-amd64.tar.gz from https://github.com/textileio/go-textile/releases
2. Run `textile wallet init` to get SOME MNEMONIC PHRASE
3. Run `textile wallet accounts "SOME MNEMONIC PHRASE" `
4. See error `textile: error: unexpected SOME MNEMONIC PHRASE, try --help`

**Expected behavior**
some ACCOUNT's public key and secret seed

**Additional context**
version 0.1.11 is good at `textile wallet accounts`

**Comment by carsonfarmer** [comment]
I think a recent change to our command line tools now requires an explicit `-p` or `--password=` flag. See `textile wallet accounts --help` for details. This _may_ need to be updated in docs.

**Comment by balupton** [comment]
Could also be a regression. Looking into it now.

**Comment by balupton** [comment]
I don't think this is a regression, but having it as a flag is silly. Will change it to an argument.

**Comment by sanderpick** [comment]
@balupton this must be related to the bug where accounts are minted with the passphrase instead of the mnemonic in versions 0.2.0 and above. Same as,

https://github.com/textileio/desktop/issues/41
https://github.com/textileio/desktop/issues/42

**Comment by balupton** [comment]
> @balupton this must be related to the bug where accounts are minted with the passphrase instead of the mnemonic in versions 0.2.0 and above. Same as,
> 
> [textileio/desktop#41](https://github.com/textileio/desktop/issues/41)
> [textileio/desktop#42](https://github.com/textileio/desktop/issues/42)

For communication clarity, those issues were [due to unescaped quotes](https://github.com/textileio/desktop/issues/41#issuecomment-500016165), and fixes are already landing.

The issue in this one is due to CLI args vs flags.
