### ISSUE TITLE
mobile: CafeSession list response missing data

### ISSUE THREAD

**Issue by asutula** [textileio/go-textile#818]
**Describe the bug**
When I query for a list of cafe sessions, the resulting session objects are missing `type`, `subject` and `rexp` values.

If I refresh the sessions individually, the updated session object that comes back has all the correct properties. 

I'd expect the session list results to include all the properties as well.

**Comment by sanderpick** [comment]
dang, that's a weird one... good catch

**Comment by sanderpick** [comment]
I looked into this and remembered that we're not actually storing the entire session object... I don't remember why TBH, but the missing values aren't actually needed to refresh the token.

A new session is added like:

```
insert or replace into cafe_sessions(cafeId, access, refresh, expiry, cafe) values(?,?,?,?,?)
```

Newly refreshed sessions return the whole object with all the values before being persisted (and losing the missing values).

We probably should fix this at some point, but doesn't feel like a priority atm... sound ok @asutula? We could just hide those values in your display UI.

**Comment by asutula** [comment]
Depends. The first things that come to mind:

1. Without the `rexp` value, I can't preemptively identify my refresh token as expired, I have to try to use it to find out.
2. Unless the server returns unique "unauthorized" error codes for expired access token vs expired refresh token, only the context of my original request can tell me which token is expired. This is manageable for more functional programming styles, but it might be harder to manage in some other scenarios, I'm not sure.

**Comment by asutula** [comment]
Those are just initial thought, could be totally off base.
