### ISSUE TITLE
mobile api: need initial sync group state event

### ISSUE THREAD

**Issue by asutula** [textileio/go-textile#829]
**Is your feature request related to a problem? Please describe.**
Yes, I'm implementing mobile file sync and it seems there is no initial event when a file is marked as `pending`.

**Describe the solution you'd like**
There should be an event fired when the first file in a group is marked as `pending`. This will notify any listener that an item is beginning to be processed.

**Comment by sanderpick** [comment]
It looks like this is already in there: https://github.com/textileio/go-textile/blob/master/mobile/cafes.go#L138 - you sure you don't see it?

**Comment by asutula** [comment]
Yea the event is already there, I see it. But I’m talking about is a method to call when the os gives me upload progress for a single  cafe request. For that single cafe request, the os will tell me like “456 bytes of 1254 total”. I want to be able to pass that information into the go api, have go incorporate that into the size complete calculation, and fire an updated status event. Make sense?

**Comment by asutula** [comment]
Cool not surprised. I probably had some other big that made me think it wasn’t there. I’ll verify and close this
