### ISSUE TITLE
mobile: need api to increment sync group size complete

### ISSUE THREAD

**Issue by asutula** [textileio/go-textile#830]
**Describe the solution you'd like**
So far, implementing the file sync api is nice because all the state is maintained in go-textile.

When processing a background upload, I get updates from the OS about the progress of file uploads in terms of how many bytes have been transferred out of how many total bytes. It would be good to incorporate that information into file sync group updates to the sdk user, but in order to do that currently, the native sdk layer will have to maintain a persistent mapping of cafe request id to sync group id. 

That state management already exists in go-textile, so it would be better to just add a mobile api method like `UpdateCafeRequestProgress(requestId string, transerred number, total number)`. When called, this would generate sync group events in which the `sizeComplete` value is updated while the `numComplete` value remains the same, giving the sdk user the most resolution into the file group progress.

**Describe alternatives you've considered**
Maintaining a map of cafe request id to group id in the native sdk. This sucks because it has to be persistent, so adds lots more complexity to the sdk and duplicates data already being persisted in go-textile.

**Additional context**
This will be awesome.

**Comment by sanderpick** [comment]
Love this... let me think about the best way here.
