### ISSUE TITLE
Any data-fetching method should be async

### ISSUE THREAD

**Issue by asutula** [textileio/go-textile#835]
**Is your feature request related to a problem? Please describe.**
All data-fetching methods are currently sync, and they can be slow it seems. This can lock up whatever thread the calls are happening on and multiple requests for data can get backed up. Methods I'm thinking of are:
```
Files.Content
Files.ImageContent
Ipfs.DataAtPath
```
Maybe there are others? You get the idea.

**Describe the solution you'd like**
These methods should be async and take a completion handler

**Comment by sanderpick** [comment]
Adding to 0.4.3...
