### ISSUE TITLE
Gateway is sending an empty Content-Type header back to a browser as opposed to a one the file should be

### ISSUE THREAD

**Issue by mysliwiec-tech** [textileio/go-textile#840]
**Describe the bug**
When my web app is downloading an mp3 file from a Textile Gateway it cannot determine it's length (in seconds) because the `Content-Type` is empty as opposed to `audio/mpeg`. All it needs to be working is the correct `Content-Type` header.

**To Reproduce**
1. Add an *.mp3 file to an encrypted thread.
2. Open a browser's Developer Tools -> Network tab.
3. Access the file through a gateway in a way as it to be downloaded.
4. In the Network tab find the file that was downloaded and verify the `Content-Type`

**Expected behavior**
I would expect that file mime/content-type will be set according to what is in the meta of the encrypted file because it is recognized properly when it's being added to a thread (correct `/meta`):
![image](https://user-images.githubusercontent.com/7201544/60178665-5e4b2500-981c-11e9-8ec2-385fda9e65f9.png)

**Screenshots**
When file is being served from a gateway, it is being served as `Content-Type: ` (just an "empty" Content-Type) 
![image](https://user-images.githubusercontent.com/7201544/60178435-df55ec80-981b-11e9-9825-4f3e60d7f61b.png)

**Tray app (please complete the following information):**

-   OS: Windows 10 Home
-   Browser: Chromium: 75.0.3770.100
-   Version: Textile Desktop v0.1.3

**Additional context**
The [sampotts/plyr](https://github.com/sampotts/plyr) library and even the standard HTML5 audio file player (build into a browser) cannot determine the *.mp3 duration and other properties of a file.
The HTML that is running the audio player. Because a file is served with a wrong `Content-Type` user cannot seek through a file. The html file that is serving a player: [index.html.txt](https://github.com/textileio/go-textile/files/3329960/index.html.txt)

**Comment by sanderpick** [comment]
Hey @mysliwiec-tech - If the content is encrypted, it doesn't make sense to me to guess the underlying content type. If you add the key, the browser can correctly sniff the type: 

https://eu-west.cafe.textile.io/ipfs/QmZxL21Veakq3k9dMtiYbp3DoT69mWTEKQCJFdkFomJV6N?key=2PVQp2JiDjcGs9o6wAQsM8HQq3SwWRiiG1FY5HWiE35zV7xPyNaDZfW26J6oE

Additionally, you can add the extension add the gateway will ignore it... this may help an older browser:

https://eu-west.cafe.textile.io/ipfs/QmZxL21Veakq3k9dMtiYbp3DoT69mWTEKQCJFdkFomJV6N.mp3?key=2PVQp2JiDjcGs9o6wAQsM8HQq3SwWRiiG1FY5HWiE35zV7xPyNaDZfW26J6oE

**Comment by mysliwiec-tech** [comment]
Seems like my previous investigation was wrong - previously I made wrong assumption. Seeking is enabled by sending 206 HTTP code and `Content-Range` header response. Do you think it will be enabled any time in the future for a gateway?

**Comment by mysliwiec-tech** [comment]
Closing as it was identified as the problem with a gateway not supporting `Range` request headers. Raised a Feature request #843
