### ISSUE TITLE
contact search returning 404 page not found

### ISSUE THREAD

**Issue by andrewxhill** [textileio/go-textile#841]
Using 0.5.0, I run,

```
textile contacts search --name="multidaft"
404 page not found
```

increasing the `wait` doesn't help, it returns immediately

**Comment by sanderpick** [comment]
Are you registered with an older cafe?

**Comment by andrewxhill** [comment]
```
            "cafe": {
                "address": "P7kneNPCLSFFWeiDj69VvjqfZqC1ru8gU5tXm5bFneY4hxpM",
                "api": "v0",
                "node": "0.2.8",
                "peer": "12D3KooWFrrmGJcQhE5h6VUvUEXdLH7gPKdWh2q4CEM62rFGcFpr",
                "protocol": "/textile/cafe/1.0.0",
                "url": "https://us-west-beta.textile.cafe"
            },
```

just tried again and it's still same error

**Comment by sanderpick** [comment]
I see... it's hitting the v0 search because that's what the session is defining. 
```
addr := fmt.Sprintf("%s/api/%s/search", session.Cafe.Url, session.Cafe.Api)
```
I didn't notice before because my tests all get a fresh session. v0 search is handled by the catch-all `/service` endpoint. We can just redirect `/v0/search` -> `/v1/search`
