### ISSUE TITLE
deeplinks handler for accepting and generating thread invites

### ISSUE THREAD

**Issue by balupton** [textileio/go-textile#849]
In the IPFS Camp workshop, creating invites to a thread was a lot more complicated than it needed to be. Obviously, this will be easier once there is a desktop GUI for go-textile, however until then, and even still, it would be nice to have the ability that when creating a thread, there was an invite URL generated with the output, or at least a deeplink to generate an invite

I would imagine this to work like `textile://invite/thread/peer` or something to that accord to generate, then `textile://join/thread/inviteid` to join.

**Comment by carsonfarmer** [comment]
Might be good to have this over in github.com/textileio/desktop as well...

**Comment by carsonfarmer** [comment]
Closing as won't fix, moving on from this approach.
