### ISSUE TITLE
Enable multi-level hierarchical accounts

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/go-textile#860]
Currently, `go-textile` utilizes a BIP32-based HD wallet (derived from a BIP39 menmonic). This allows us to create 'deep' nested wallet accounts as needed. However, our implementation currently only supports a single depth. While this is likely sufficient for 99% of use-cases, there are some use-cases that would benefit from deeper nesting. This ticket is a reminder to add support for deeper nesting.

For external devs: If deeper nesting is important to you, please let us know, as this is currently not a big priority for us without additional concrete use-cases.

**Comment by andrewxhill** [comment]
one of the concepts that came up on our team call 2-3 weeks ago was reserving the next layer for apps. so each app would be siloed by connected to the account... i think it could be worth scoping this out more. user to many accounts. an account to many apps.

**Comment by carsonfarmer** [comment]
Related to #862

**Comment by carsonfarmer** [comment]
Related to some recent discussions on Slack, plus the comment from @andrewxhill above. What about reserving a set of addresses for 'network'/'textile' functions, and then exposing the remaining 'space' to applications? The need for multi-level permissions and keys has come up several times now, so it would be useful to explore this again.

**Comment by andrewxhill** [comment]
are there existing wallets that do this? follow-up, can we enable support for those wallets?

**Comment by carsonfarmer** [comment]
Closing this in favour of "Supporting External Wallets": https://github.com/textileio/go-threads/issues/225
