### ISSUE TITLE
You can't create new threads and invite people to them

### ISSUE THREAD

**Issue by sanderpick** [textileio/go-textile#883]
@andrewxhill commented on [Tue Jul 30 2019](https://github.com/textileio/photos/issues/1260)

## On production Textile between 2 devices:

1. Create a brand new thread. Don't bother adding anything to it (or do if you like).
2. Invite a peer to that thread via a p2p invite.
3. Go to peer's phone.
4. Accept invite
5. When peer joins the thread, they will see only themselves having joined.
6. Refresh the app (or hardkill and reopen). 
7. The peer will see, 

![Screen Shot 2019-07-30 at 10 59 23 AM](https://user-images.githubusercontent.com/370259/62153303-1d31af00-b2b9-11e9-9170-212d6a0b5c81.png)

## On production from device to daemon

I performed a similar set of steps as above, but this time invited p2p my user that is on my desktop daemon. 

In this case, I think it appears to join the thread successfully and I don't see anything particularly corrupt. Post `thread accept invite <id>` I do,

```
textile threads get 12D3KooWLz2DsLkQvLYLNQoPe523abTft51qCGkZ8caEbqDnfbgC
{
    "block_count": 3,
    "head": "Qma5hLAN4GZ3d7ytR69hNayPBpq4EXF6QJCMvf1gy5337w",
    "head_blocks": [
        {
            "author": "12D3KooWB32CouwnXVxf6r1DhCm5F2Dbte2xPCGzsEHjgLUubkZ1",
            "date": "2019-07-30T17:32:50.121810Z",
            "id": "QmasvJ6ruY6fW5QGLPp54ESUgCsha6S6H7Ua8htyPXD4SR",
            "parents": [
                "QmdsvGfzSspnWbAhZUTPMBhH9GMC2JwNZyQ8QV6ZCqS8sy"
            ],
            "thread": "12D3KooWLz2DsLkQvLYLNQoPe523abTft51qCGkZ8caEbqDnfbgC",
            "type": "JOIN",
            "user": {
                "address": "P4pcJ2E15nmYVXRPbb7hX9pn3Kjv1UNZQkninyUWaPvjnMtm",
                "avatar": "QmW3caygKdzENxuErEPwBip4Z8N7FbPRx7gAbJ9ScYTjwk",
                "name": "IPFSCamper"
            }
        }
    ],
    "id": "12D3KooWLz2DsLkQvLYLNQoPe523abTft51qCGkZ8caEbqDnfbgC",
    "initiator": "P4hyTD7oh5D39y5t7rXevEnRNo5ExLXbfC2H9sf6g6KLo5AP",
    "key": "textile_photos-shared-744e0c9c-270d-45d8-821e-d973822677fe",
    "name": "LOL",
    "peer_count": 2,
    "schema": "QmeVa8vUbyjHaYaeki8RZRshsn3JeYGi8QCnLCWXh6euEh",
    "schema_node": {
        "links": {
            "large": {
                "mill": "/image/resize",
                "opts": {
                    "quality": "80",
                    "width": "800"
                },
                "use": ":file"
            },
            "small": {
                "mill": "/image/resize",
                "opts": {
                    "quality": "80",
                    "width": "320"
                },
                "use": ":file"
            },
            "thumb": {
                "mill": "/image/resize",
                "opts": {
                    "quality": "80",
                    "width": "100"
                },
                "pin": true,
                "use": "large"
            }
        },
        "name": "media",
        "pin": true
    },
    "sharing": "SHARED",
    "sk": "CAESQJspta1gKKj5u+NcbHhzKwZ+ScfBp54F27nE2H+x97vPpenPpVV0TLqENxJO7n4i5tn2YNEfCX1aaHBAa8OmNOk=",
    "state": "LOADED",
    "type": "OPEN",
    "whitelist": []
}
```

## Via QR Code / Link based invite between 2 phones

1. I do the above, but instead of doing a p2p invite I generated a link.
2. When second phone joins the thread, it appears to do so successfully.
3. There is no warning of a corrupt thread.

However, the two peers seem to be on detached heads. I can't get them to reconcile. 
**This final case we can probably ignore until threads v2**

---

@asutula commented on [Tue Jul 30 2019](https://github.com/textileio/photos/issues/1260#issuecomment-516542897)

Little info here... We are displaying that alert icon on the group when we detect the thread is invalid because:
```
const valid = thread.headBlocks.length > 0
```
That's what @sanderpick said to use, I don't claim to understand the reasoning or what the different situations are that lead to different states of `headBlocks`

---

@sanderpick commented on [Wed Jul 31 2019](https://github.com/textileio/photos/issues/1260#issuecomment-516906118)

Can I see some logs from the peer that is seeing the error?

---

@sanderpick commented on [Wed Jul 31 2019](https://github.com/textileio/photos/issues/1260#issuecomment-516906413)

(I'm unable to reproduce)

---

@sanderpick commented on [Wed Jul 31 2019](https://github.com/textileio/photos/issues/1260#issuecomment-516907035)

Additionally, does it happen on latest beta?

---

@andrewxhill commented on [Wed Jul 31 2019](https://github.com/textileio/photos/issues/1260#issuecomment-516955256)

your latest invite to me failed. trying to pull logs now. could you invite "andrew v2" to that same group?

![IMG_B5B1BBB3A930-1](https://user-images.githubusercontent.com/370259/62235495-f5f2e480-b381-11e9-85e2-eb85a1f4e910.jpeg)

---

@andrewxhill commented on [Wed Jul 31 2019](https://github.com/textileio/photos/issues/1260#issuecomment-516955722)

you successfully joined "Tesst"?

**Comment by sanderpick** [comment]
Moved to https://github.com/textileio/go-textile/issues/883

**Comment by sanderpick** [comment]
The issue seems to be related to the block sync and commit mechanics. A block is only ever placed in the outbox (destined for a direct send, pubsub, or peer inbox) after it has been committed to a thread, which happens after any sync operations. A block can be synced and committed to a thread before its parent. This is intentional as the queued blocks are handed concurrently. However, in this case the invite is synced and committed before the join block is synced and committed, which means the invitee will never find the join and signal to the inviter that they have joined.

https://github.com/textileio/go-textile/pull/882 postpones committing if the block is not a join and it would result in a parent-less entry.

**Comment by sanderpick** [comment]
Question @andrewxhill - when you see this, does the thread list hang for a few seconds or does it display immediately?

**Comment by andrewxhill** [comment]
if you mean on an app reload event, then yes I started noticing my app hanging more (even after launch) at the group list screen than I remember previously. 

if you mean, at the time of accepting the invite, I notice that the invite accepts at normal speed and then drops me into what appears to be a successful group created. if i exit, the groups are already visible so no full fetch needed or lag notices.

on refresh of the app, i notice the first point, app restarts then there seems be some log loading my groups. finally, my newly entered group is marked as corrupt once it is displayed

**Comment by sanderpick** [comment]
10 4, thanks. There may be two issues here:
- A block commit race - fixed by https://github.com/textileio/go-textile/pull/882
- The initial block was not pinned - this may be fixed by https://github.com/textileio/go-textile/pull/882 as well, but I'm not certain. In any case, I still cannot reproduce over here, which means I'm having a hard time coming up with other ideas.

I'm gonna release - I should be in a better spot to track this down with the above in place.
