### ISSUE TITLE
CircleCI unit-test with Go 1.13 image

### ISSUE THREAD

**Issue by jsign** [textileio/go-textile#918]
To migrate CircleCI to compile with Go 1.13:
- [ ] Create a new `textile/builder` docker image
- [ ] Change `.circleci/config.yaml` to use it

**Comment by jsign** [comment]
Regarding the first checklist item:
@sanderpick , is the `textile/builder` Dockerfile available?
I imagine is just changing the [URL tar file](https://golang.org/dl/), rebuild, tag and upload.

**Comment by sanderpick** [comment]
Yep, the file is here: https://github.com/textileio/go-textile/blob/master/.circleci/Dockerfile

After re-building that image, you should now be able to push a new tag to docker hub

**Comment by jsign** [comment]
Nice. I'll let you know about any probs.
